// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cometbft/multiplex/v1/archive.proto

package v1

import (
	fmt "fmt"
	v11 "github.com/cometbft/cometbft/api/cometbft/p2p/v1"
	v1 "github.com/cometbft/cometbft/api/cometbft/state/v1"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// HistoricalState contains a sm.State and a custom data payload.
type HistoricalState struct {
	State v1.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
	Data  []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *HistoricalState) Reset()         { *m = HistoricalState{} }
func (m *HistoricalState) String() string { return proto.CompactTextString(m) }
func (*HistoricalState) ProtoMessage()    {}
func (*HistoricalState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f105e01105ed4df, []int{0}
}
func (m *HistoricalState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalState.Merge(m, src)
}
func (m *HistoricalState) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalState) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalState.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalState proto.InternalMessageInfo

func (m *HistoricalState) GetState() v1.State {
	if m != nil {
		return m.State
	}
	return v1.State{}
}

func (m *HistoricalState) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// HistoricalNodeInfo is the node information exchanged by historical nodes
// of a multi-network infra during the CometBFT P2P handshake.
type HistoricalNodeInfo struct {
	Networks         []string                 `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	ProtocolVersions []*ChainProtocolVersion  `protobuf:"bytes,2,rep,name=protocol_versions,json=protocolVersions,proto3" json:"protocol_versions,omitempty"`
	DefaultNodeID    string                   `protobuf:"bytes,3,opt,name=default_node_id,json=defaultNodeId,proto3" json:"default_node_id,omitempty"`
	ListenAddr       string                   `protobuf:"bytes,4,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Version          string                   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Channels         []byte                   `protobuf:"bytes,6,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker          string                   `protobuf:"bytes,7,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other            v11.DefaultNodeInfoOther `protobuf:"bytes,8,opt,name=other,proto3" json:"other"`
}

func (m *HistoricalNodeInfo) Reset()         { *m = HistoricalNodeInfo{} }
func (m *HistoricalNodeInfo) String() string { return proto.CompactTextString(m) }
func (*HistoricalNodeInfo) ProtoMessage()    {}
func (*HistoricalNodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f105e01105ed4df, []int{1}
}
func (m *HistoricalNodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalNodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalNodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalNodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalNodeInfo.Merge(m, src)
}
func (m *HistoricalNodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalNodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalNodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalNodeInfo proto.InternalMessageInfo

func (m *HistoricalNodeInfo) GetNetworks() []string {
	if m != nil {
		return m.Networks
	}
	return nil
}

func (m *HistoricalNodeInfo) GetProtocolVersions() []*ChainProtocolVersion {
	if m != nil {
		return m.ProtocolVersions
	}
	return nil
}

func (m *HistoricalNodeInfo) GetDefaultNodeID() string {
	if m != nil {
		return m.DefaultNodeID
	}
	return ""
}

func (m *HistoricalNodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *HistoricalNodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *HistoricalNodeInfo) GetChannels() []byte {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *HistoricalNodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *HistoricalNodeInfo) GetOther() v11.DefaultNodeInfoOther {
	if m != nil {
		return m.Other
	}
	return v11.DefaultNodeInfoOther{}
}

func init() {
	proto.RegisterType((*HistoricalState)(nil), "cometbft.multiplex.v1.HistoricalState")
	proto.RegisterType((*HistoricalNodeInfo)(nil), "cometbft.multiplex.v1.HistoricalNodeInfo")
}

func init() {
	proto.RegisterFile("cometbft/multiplex/v1/archive.proto", fileDescriptor_9f105e01105ed4df)
}

var fileDescriptor_9f105e01105ed4df = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x8b, 0x13, 0x31,
	0x18, 0xed, 0xf4, 0xc7, 0xfe, 0x48, 0x5d, 0xd6, 0x0d, 0x0a, 0xa1, 0xe2, 0x74, 0x5c, 0x11, 0x06,
	0x84, 0x19, 0x5a, 0x45, 0xf0, 0xb8, 0x75, 0x0f, 0x7a, 0xd1, 0x65, 0x04, 0x11, 0x3d, 0x94, 0x74,
	0x92, 0x76, 0xc2, 0x4e, 0x93, 0x90, 0xa4, 0xa3, 0xfe, 0x17, 0xfe, 0x59, 0x7b, 0xdc, 0xa3, 0xa7,
	0x45, 0xda, 0xbf, 0xc2, 0x9b, 0x24, 0xd3, 0xa6, 0x55, 0x7a, 0xcb, 0xfb, 0xde, 0x7b, 0x5f, 0xde,
	0xf7, 0x25, 0xe0, 0x69, 0x2e, 0xe6, 0xd4, 0x4c, 0xa6, 0x26, 0x9d, 0x2f, 0x4a, 0xc3, 0x64, 0x49,
	0xbf, 0xa7, 0xd5, 0x20, 0xc5, 0x2a, 0x2f, 0x58, 0x45, 0x13, 0xa9, 0x84, 0x11, 0xf0, 0xe1, 0x46,
	0x94, 0x78, 0x51, 0x52, 0x0d, 0x7a, 0x0f, 0x66, 0x62, 0x26, 0x9c, 0x22, 0xb5, 0xa7, 0x5a, 0xdc,
	0x7b, 0xec, 0x3b, 0x6a, 0x83, 0x0d, 0xb5, 0xdd, 0xcc, 0x0f, 0x49, 0xf5, 0x9a, 0x7e, 0xe4, 0x69,
	0x39, 0x94, 0xff, 0x93, 0x4f, 0xf6, 0xa7, 0xd9, 0x91, 0x9c, 0x7f, 0x05, 0xa7, 0x6f, 0x99, 0x36,
	0x42, 0xb1, 0x1c, 0x97, 0x1f, 0xed, 0x0d, 0xf0, 0x25, 0xe8, 0xb8, 0xab, 0x50, 0x10, 0x05, 0x71,
	0x77, 0x88, 0x12, 0x1f, 0xd7, 0x95, 0x93, 0x6a, 0x90, 0x38, 0xe1, 0xa8, 0x7d, 0x73, 0xd7, 0x6f,
	0x64, 0xb5, 0x18, 0x42, 0xd0, 0x26, 0xd8, 0x60, 0xd4, 0x8c, 0x82, 0xf8, 0x5e, 0xe6, 0xce, 0xe7,
	0x7f, 0x9a, 0x00, 0x6e, 0xbb, 0xbf, 0x17, 0x84, 0xbe, 0xe3, 0x53, 0x01, 0x7b, 0xe0, 0x88, 0x53,
	0xf3, 0x4d, 0xa8, 0x6b, 0x8d, 0x82, 0xa8, 0x15, 0x1f, 0x67, 0x1e, 0xc3, 0xcf, 0xe0, 0xcc, 0x05,
	0xcb, 0x45, 0x39, 0xae, 0xa8, 0xd2, 0x4c, 0x70, 0x8d, 0x9a, 0x51, 0x2b, 0xee, 0x0e, 0x9f, 0x27,
	0x7b, 0xf7, 0x96, 0xbc, 0x29, 0x30, 0xe3, 0x57, 0x6b, 0xd3, 0xa7, 0xda, 0x93, 0xdd, 0x97, 0xff,
	0x16, 0x34, 0x7c, 0x0d, 0x4e, 0x09, 0x9d, 0xe2, 0x45, 0x69, 0xc6, 0x5c, 0x10, 0x3a, 0x66, 0x04,
	0xb5, 0xa2, 0x20, 0x3e, 0x1e, 0x9d, 0x2d, 0xef, 0xfa, 0x27, 0x97, 0x35, 0xe5, 0x32, 0x5e, 0x66,
	0x27, 0x64, 0x07, 0x12, 0xd8, 0x07, 0xdd, 0x92, 0x69, 0x43, 0xf9, 0x18, 0x13, 0xa2, 0x50, 0xdb,
	0xda, 0x32, 0x50, 0x97, 0x2e, 0x08, 0x51, 0x10, 0x81, 0xc3, 0x75, 0x58, 0xd4, 0x71, 0xe4, 0x06,
	0xda, 0x59, 0xf3, 0x02, 0x73, 0x4e, 0x4b, 0x8d, 0x0e, 0xdc, 0x6a, 0x3c, 0xb6, 0xae, 0xb9, 0xe0,
	0xec, 0x9a, 0x2a, 0x74, 0x58, 0xbb, 0xd6, 0x10, 0x5e, 0x80, 0x8e, 0x30, 0x05, 0x55, 0xe8, 0xc8,
	0x3d, 0xc1, 0xb3, 0xed, 0xe4, 0x72, 0x28, 0xed, 0xcc, 0xbb, 0x71, 0xf9, 0x54, 0x7c, 0xb0, 0xe2,
	0xcd, 0x7b, 0x38, 0xe7, 0xe8, 0xea, 0x66, 0x19, 0x06, 0xb7, 0xcb, 0x30, 0xf8, 0xbd, 0x0c, 0x83,
	0x9f, 0xab, 0xb0, 0x71, 0xbb, 0x0a, 0x1b, 0xbf, 0x56, 0x61, 0xe3, 0xcb, 0xab, 0x19, 0x33, 0xc5,
	0x62, 0x62, 0x7b, 0xa6, 0xfe, 0x83, 0xf8, 0x03, 0x96, 0x2c, 0xdd, 0xfb, 0x6d, 0x26, 0x07, 0x6e,
	0xa5, 0x2f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xf7, 0x27, 0xab, 0xe4, 0x02, 0x00, 0x00,
}

func (m *HistoricalState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintArchive(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *HistoricalNodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalNodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalNodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Other.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintArchive(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Channels) > 0 {
		i -= len(m.Channels)
		copy(dAtA[i:], m.Channels)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.Channels)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ListenAddr) > 0 {
		i -= len(m.ListenAddr)
		copy(dAtA[i:], m.ListenAddr)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.ListenAddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DefaultNodeID) > 0 {
		i -= len(m.DefaultNodeID)
		copy(dAtA[i:], m.DefaultNodeID)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.DefaultNodeID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProtocolVersions) > 0 {
		for iNdEx := len(m.ProtocolVersions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProtocolVersions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintArchive(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Networks) > 0 {
		for iNdEx := len(m.Networks) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Networks[iNdEx])
			copy(dAtA[i:], m.Networks[iNdEx])
			i = encodeVarintArchive(dAtA, i, uint64(len(m.Networks[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintArchive(dAtA []byte, offset int, v uint64) int {
	offset -= sovArchive(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HistoricalState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovArchive(uint64(l))
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	return n
}

func (m *HistoricalNodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Networks) > 0 {
		for _, s := range m.Networks {
			l = len(s)
			n += 1 + l + sovArchive(uint64(l))
		}
	}
	if len(m.ProtocolVersions) > 0 {
		for _, e := range m.ProtocolVersions {
			l = e.Size()
			n += 1 + l + sovArchive(uint64(l))
		}
	}
	l = len(m.DefaultNodeID)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.ListenAddr)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.Channels)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = m.Other.Size()
	n += 1 + l + sovArchive(uint64(l))
	return n
}

func sovArchive(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozArchive(x uint64) (n int) {
	return sovArchive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HistoricalState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArchive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArchive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistoricalNodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalNodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalNodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Networks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Networks = append(m.Networks, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolVersions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtocolVersions = append(m.ProtocolVersions, &ChainProtocolVersion{})
			if err := m.ProtocolVersions[len(m.ProtocolVersions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultNodeID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultNodeID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListenAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListenAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channels", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channels = append(m.Channels[:0], dAtA[iNdEx:postIndex]...)
			if m.Channels == nil {
				m.Channels = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Other", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Other.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArchive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArchive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipArchive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthArchive
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupArchive
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthArchive
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthArchive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowArchive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupArchive = fmt.Errorf("proto: unexpected end of group")
)
